import type { CardioScenario } from '@/lib/cardio-types';

const baseVersions = {
  engine: '1.0.0-cardio-demo',
  ruleset: '1.0.0-cardio-demo',
  safety_policy: '1.0.0-cardio-demo',
  contract: 'cardio_triage_report_v1',
};

const policyEvaluated = [
  'POLICY_SYNCOPAL_CHEST_PAIN_V1',
  'POLICY_SEVERE_ONGOING_CHEST_PAIN_V1',
  'POLICY_VERY_LOW_BP_V1',
  'POLICY_TACHYCARDIA_WITH_CONCERNING_SYMPTOMS_V1',
  'POLICY_DYSPNEA_CHEST_PAIN_HIGH_RISK_V1',
];

const rulesEvaluated = [
  'RULE_URGENT_EXERTIONAL_RADIATION_V1',
  'RULE_URGENT_SYMPTOM_RISK_CLUSTER_V1',
  'RULE_URGENT_NON_CATASTROPHIC_VITALS_V1',
  'RULE_ROUTINE_STABLE_COMPLETE_V1',
];

export const cardioScenarios: CardioScenario[] = [
  {
    id: 'NEEDS_MORE_INFO',
    label: 'Needs More Info',
    report: {
      ok: true,
      errors: [],
      versions: baseVersions,
      decision: {
        status: 'NEEDS_MORE_INFO',
        decision_type: 'NEEDS_MORE_INFO',
        decision_id: 'READINESS_INCOMPLETE',
        path: null,
        recommended_route: null,
        case_status: 'PENDING_DATA',
        urgency_level: 'UNKNOWN',
        clinical_summary: 'Critical cardio fields missing; safe routing deferred.',
        required_fields: ['pain_duration_minutes', 'pain_character', 'pain_radiation', 'prior_mi_or_known_cad'],
        missing_fields: ['pain_duration_minutes', 'pain_character', 'pain_radiation', 'prior_mi_or_known_cad'],
        required_actions: ['Collect all listed missing critical fields and resubmit.'],
        reasons: [],
        flags: [],
      },
      safety: {
        status: 'CLEAR',
        action: 'NONE',
        triggers: [],
        policy_version: '1.0.0-cardio-demo',
        safety_id: 'NONE',
        has_red_flags: false,
        override_applied: false,
        severity: 'NONE',
        flags: [],
      },
      trace: {
        policy_trace: { evaluated: policyEvaluated, triggered: [] },
        rules_evaluated: rulesEvaluated,
        rules_triggered: [],
        activated_rules: [],
        evidence: {
          chest_pain_present: { value: true },
          syncope: { value: false },
        },
        uncertainty_notes: ['Critical cardio fields missing; triage logic not executed.'],
        missing_fields: ['pain_duration_minutes', 'pain_character', 'pain_radiation', 'prior_mi_or_known_cad'],
        conflicts_detected: [],
        preliminary_route: null,
        final_route: null,
        override_reason: null,
      },
    },
  },
  {
    id: 'ROUTINE_REVIEW',
    label: 'Routine Review',
    report: {
      ok: true,
      errors: [],
      versions: baseVersions,
      decision: {
        status: 'DECIDED',
        decision_type: 'ROUTINE_REVIEW',
        decision_id: 'ROUTINE_REVIEW',
        path: 'PATH_ROUTINE',
        recommended_route: 'PATH_ROUTINE',
        case_status: 'TRIAGED',
        urgency_level: 'ROUTINE',
        clinical_summary: 'Stable complete case; routine review indicated by deterministic rules.',
        required_fields: [],
        missing_fields: [],
        required_actions: ['Schedule routine cardiology review.'],
        reasons: ['No emergency or urgent cluster detected in complete case.'],
        flags: [],
      },
      safety: {
        status: 'CLEAR',
        action: 'NONE',
        triggers: [],
        policy_version: '1.0.0-cardio-demo',
        safety_id: 'NONE',
        has_red_flags: false,
        override_applied: false,
        severity: 'NONE',
        flags: [],
      },
      trace: {
        policy_trace: { evaluated: policyEvaluated, triggered: [] },
        rules_evaluated: rulesEvaluated,
        rules_triggered: ['RULE_ROUTINE_STABLE_COMPLETE_V1'],
        activated_rules: ['RULE_ROUTINE_STABLE_COMPLETE_V1'],
        evidence: {
          pain_character: { value: 'pressure' },
          pain_radiation: { value: 'none' },
        },
        uncertainty_notes: [],
        missing_fields: [],
        conflicts_detected: [],
        preliminary_route: 'PATH_ROUTINE',
        final_route: 'PATH_ROUTINE',
        override_reason: null,
      },
    },
  },
  {
    id: 'URGENT_ESCALATION',
    label: 'Urgent Escalation',
    report: {
      ok: true,
      errors: [],
      versions: baseVersions,
      decision: {
        status: 'DECIDED',
        decision_type: 'URGENT_ESCALATION',
        decision_id: 'URGENT_ESCALATION',
        path: 'PATH_URGENT_SAME_DAY',
        recommended_route: 'PATH_URGENT_SAME_DAY',
        case_status: 'TRIAGED',
        urgency_level: 'URGENT',
        clinical_summary: 'Urgent same-day review indicated by deterministic risk rule(s).',
        required_fields: [],
        missing_fields: [],
        required_actions: ['Arrange same-day clinical escalation pathway.'],
        reasons: ['Exertional chest pain with arm/jaw radiation.'],
        flags: [],
      },
      safety: {
        status: 'CLEAR',
        action: 'NONE',
        triggers: [],
        policy_version: '1.0.0-cardio-demo',
        safety_id: 'NONE',
        has_red_flags: false,
        override_applied: false,
        severity: 'NONE',
        flags: [],
      },
      trace: {
        policy_trace: { evaluated: policyEvaluated, triggered: [] },
        rules_evaluated: rulesEvaluated,
        rules_triggered: ['RULE_URGENT_EXERTIONAL_RADIATION_V1'],
        activated_rules: ['RULE_URGENT_EXERTIONAL_RADIATION_V1'],
        evidence: {
          exertional_chest_pain: { value: true },
          pain_radiation: { value: 'jaw' },
        },
        uncertainty_notes: [],
        missing_fields: [],
        conflicts_detected: [],
        preliminary_route: 'PATH_URGENT_SAME_DAY',
        final_route: 'PATH_URGENT_SAME_DAY',
        override_reason: null,
      },
    },
  },
  {
    id: 'EMERGENCY_ROUTE',
    label: 'Emergency Route',
    report: {
      ok: true,
      errors: [],
      versions: baseVersions,
      decision: {
        status: 'ESCALATED',
        decision_type: 'EMERGENCY_OVERRIDE',
        decision_id: 'EMERGENCY_OVERRIDE',
        path: 'PATH_EMERGENCY_NOW',
        recommended_route: 'PATH_EMERGENCY_NOW',
        case_status: 'TRIAGED',
        urgency_level: 'EMERGENCY',
        clinical_summary: 'Hard emergency red-flag criteria met; emergency route required.',
        required_fields: [],
        missing_fields: [],
        required_actions: ['Initiate immediate emergency escalation protocol.'],
        reasons: [],
        flags: ['FLAG_SYNCOPAL_CHEST_PAIN'],
      },
      safety: {
        status: 'TRIGGERED',
        action: 'OVERRIDE_ESCALATE',
        triggers: ['POLICY_SYNCOPAL_CHEST_PAIN_V1'],
        policy_version: '1.0.0-cardio-demo',
        safety_id: 'EMERGENCY_HARD_RED_FLAG',
        has_red_flags: true,
        override_applied: true,
        severity: 'EMERGENCY',
        flags: ['FLAG_SYNCOPAL_CHEST_PAIN'],
      },
      trace: {
        policy_trace: { evaluated: policyEvaluated, triggered: ['POLICY_SYNCOPAL_CHEST_PAIN_V1'] },
        rules_evaluated: rulesEvaluated,
        rules_triggered: ['RULE_ROUTINE_STABLE_COMPLETE_V1'],
        activated_rules: ['RULE_ROUTINE_STABLE_COMPLETE_V1', 'POLICY_SYNCOPAL_CHEST_PAIN_V1'],
        evidence: {
          syncope: { value: true },
          chest_pain_present: { value: true },
        },
        uncertainty_notes: [],
        missing_fields: [],
        conflicts_detected: [],
        preliminary_route: 'PATH_ROUTINE',
        final_route: 'PATH_EMERGENCY_NOW',
        override_reason: 'Hard red-flag emergency criteria met.',
      },
    },
  },
  {
    id: 'DEFERRED_PENDING_DATA',
    label: 'Deferred Pending Data',
    report: {
      ok: true,
      errors: [],
      versions: baseVersions,
      decision: {
        status: 'CONFLICT',
        decision_type: 'DEFERRED_PENDING_DATA',
        decision_id: 'DEFERRED_PENDING_DATA',
        path: null,
        recommended_route: null,
        case_status: 'PENDING_DATA',
        urgency_level: 'UNKNOWN',
        clinical_summary: 'Conflicting structured cardio inputs detected; safe routing deferred.',
        required_fields: [],
        missing_fields: [],
        required_actions: [
          'Reconcile contradictory chest-pain fields.',
          'Reconfirm symptom presence, severity, and related attributes.',
        ],
        reasons: [],
        flags: [],
      },
      safety: {
        status: 'CLEAR',
        action: 'NONE',
        triggers: [],
        policy_version: '1.0.0-cardio-demo',
        safety_id: 'NONE',
        has_red_flags: false,
        override_applied: false,
        severity: 'NONE',
        flags: [],
      },
      trace: {
        policy_trace: { evaluated: policyEvaluated, triggered: [] },
        rules_evaluated: rulesEvaluated,
        rules_triggered: ['RULE_ROUTINE_STABLE_COMPLETE_V1'],
        activated_rules: ['RULE_ROUTINE_STABLE_COMPLETE_V1'],
        evidence: {
          chest_pain_present: { value: false },
          pain_character: { value: 'crushing' },
        },
        uncertainty_notes: ['Conflicting structured inputs detected.'],
        missing_fields: [],
        conflicts_detected: [
          'CONFLICT_PAIN_SEVERITY_WITHOUT_CHEST_PAIN',
          'CONFLICT_PAIN_DURATION_WITHOUT_CHEST_PAIN',
          'CONFLICT_PAIN_CHARACTER_WITHOUT_CHEST_PAIN',
          'CONFLICT_RADIATION_WITHOUT_CHEST_PAIN',
        ],
        preliminary_route: 'PATH_ROUTINE',
        final_route: null,
        override_reason: null,
      },
    },
  },
];
