from __future__ import annotations

# Version pins (stage-1 scaffold: intentionally fixed/stable)
ENGINE_VERSION = "1.0.0-cardio-scaffold"
RULESET_VERSION = "1.0.0-cardio-scaffold"
SAFETY_POLICY_VERSION = "1.0.0-cardio-scaffold"
CONTRACT_VERSION = "cardio_triage_report_v1"

# Decision statuses
DECISION_DECIDED = "DECIDED"
DECISION_NEEDS_MORE_INFO = "NEEDS_MORE_INFO"
DECISION_CONFLICT = "CONFLICT"
DECISION_ESCALATED = "ESCALATED"
DECISION_STATUSES = {
    DECISION_DECIDED,
    DECISION_NEEDS_MORE_INFO,
    DECISION_CONFLICT,
    DECISION_ESCALATED,
}

# Deterministic triage routes (IDs are intentionally fixed)
PATH_MORE_QUESTIONS = "PATH_MORE_QUESTIONS"
PATH_EMERGENCY_NOW = "PATH_EMERGENCY_NOW"
PATH_URGENT_SAME_DAY = "PATH_URGENT_SAME_DAY"
PATH_ROUTINE = "PATH_ROUTINE"
PATH_SELF_CARE = "PATH_SELF_CARE"
PATH_ESCALATE_HUMAN = "PATH_ESCALATE_HUMAN"
ALL_PATH_IDS = [
    PATH_MORE_QUESTIONS,
    PATH_EMERGENCY_NOW,
    PATH_URGENT_SAME_DAY,
    PATH_ROUTINE,
    PATH_SELF_CARE,
    PATH_ESCALATE_HUMAN,
]

# Safety statuses/actions
SAFETY_CLEAR = "CLEAR"
SAFETY_TRIGGERED = "TRIGGERED"
SAFETY_STATUSES = {SAFETY_CLEAR, SAFETY_TRIGGERED}

SAFETY_ACTION_NONE = "NONE"
SAFETY_ACTION_OVERRIDE_ESCALATE = "OVERRIDE_ESCALATE"
SAFETY_ACTION_OVERRIDE_BLOCK_RECS = "OVERRIDE_BLOCK_RECS"
SAFETY_ACTIONS = {
    SAFETY_ACTION_NONE,
    SAFETY_ACTION_OVERRIDE_ESCALATE,
    SAFETY_ACTION_OVERRIDE_BLOCK_RECS,
}

# Rule IDs reserved for cardiology triage (not executed in stage 1)
RULE_CHEST_PAIN_HIGH_RISK_V1 = "RULE_CHEST_PAIN_HIGH_RISK_V1"
RULE_HEMODYNAMIC_INSTABILITY_V1 = "RULE_HEMODYNAMIC_INSTABILITY_V1"
RULE_ARRHYTHMIA_SYMPTOMATIC_V1 = "RULE_ARRHYTHMIA_SYMPTOMATIC_V1"
RULE_STABLE_LOW_RISK_V1 = "RULE_STABLE_LOW_RISK_V1"
ALL_RULE_IDS = [
    RULE_CHEST_PAIN_HIGH_RISK_V1,
    RULE_HEMODYNAMIC_INSTABILITY_V1,
    RULE_ARRHYTHMIA_SYMPTOMATIC_V1,
    RULE_STABLE_LOW_RISK_V1,
]

# Safety policy IDs reserved for cardiology triage
POLICY_ACUTE_MI_RED_FLAG_V1 = "POLICY_ACUTE_MI_RED_FLAG_V1"
POLICY_SHOCK_RED_FLAG_V1 = "POLICY_SHOCK_RED_FLAG_V1"
POLICY_NEUROVASCULAR_RED_FLAG_V1 = "POLICY_NEUROVASCULAR_RED_FLAG_V1"
ALL_POLICY_RULE_IDS = [
    POLICY_ACUTE_MI_RED_FLAG_V1,
    POLICY_SHOCK_RED_FLAG_V1,
    POLICY_NEUROVASCULAR_RED_FLAG_V1,
]

# Trace section keys (fixed)
TRACE_KEY_POLICY_TRACE = "policy_trace"
TRACE_KEY_RULES_EVALUATED = "rules_evaluated"
TRACE_KEY_RULES_TRIGGERED = "rules_triggered"
TRACE_KEY_EVIDENCE = "evidence"
TRACE_KEY_UNCERTAINTY_NOTES = "uncertainty_notes"
TRACE_SECTION_KEYS = [
    TRACE_KEY_POLICY_TRACE,
    TRACE_KEY_RULES_EVALUATED,
    TRACE_KEY_RULES_TRIGGERED,
    TRACE_KEY_EVIDENCE,
    TRACE_KEY_UNCERTAINTY_NOTES,
]

REPORT_TOP_LEVEL_KEYS = ["ok", "errors", "versions", "decision", "safety", "trace"]
