from __future__ import annotations

ENGINE_VERSION = "1.0.0-pen-hair-demo"
RULESET_VERSION = "1.0.0-pen-hair-demo"
SAFETY_POLICY_VERSION = "1.0.0-pen-hair-demo"
CONTRACT_VERSION = "pen_hair_report_v1"

DECISION_STATUS_DECIDED = "DECIDED"
DECISION_STATUS_NEEDS_MORE_INFO = "NEEDS_MORE_INFO"

DECISION_PATH_TOPICAL_TREATMENT = "topical_treatment"
DECISION_PATH_ORAL_TREATMENT = "oral_treatment"

SAFETY_FLAG_HIGH_BLOOD_PRESSURE = "HIGH_BLOOD_PRESSURE"
EXCLUDED_OPTION_ORAL_TREATMENT = DECISION_PATH_ORAL_TREATMENT

RULE_EXCLUDE_ORAL_FOR_HYPERTENSION = "RULE_EXCLUDE_ORAL_FOR_HYPERTENSION_V1"
RULE_DEFAULT_SAFEST_START = "RULE_DEFAULT_SAFEST_START_V1"

JOURNEY_STATES = ["month_0", "week_6", "month_3", "month_6"]
