from __future__ import annotations

ENGINE_VERSION = "1.2.0-pen-hair-demo"
RULESET_VERSION = "1.2.0-pen-hair-demo"
SAFETY_POLICY_VERSION = "1.2.0-pen-hair-demo"
CONTRACT_VERSION = "pen_hair_report_v1.2"

DECISION_STATUS_DECIDED = "DECIDED"
DECISION_STATUS_NEEDS_MORE_INFO = "NEEDS_MORE_INFO"

DECISION_PATH_TOPICAL_TREATMENT = "topical_treatment"
DECISION_PATH_TOPICAL_TREATMENT_WITH_SUPPORT = "topical_treatment_with_support"
DECISION_PATH_NEEDS_MORE_INFORMATION = "needs_more_information"
DECISION_PATH_MANUAL_REVIEW = "manual_review"
DECISION_PATH_ORAL_TREATMENT = "oral_treatment"

SAFETY_FLAG_HIGH_BLOOD_PRESSURE = "HIGH_BLOOD_PRESSURE"
SAFETY_FLAG_CARDIOVASCULAR_CONDITION = "CARDIOVASCULAR_CONDITION"
SAFETY_FLAG_PRIOR_SIDE_EFFECTS = "PRIOR_SIDE_EFFECTS"
SAFETY_FLAG_SCALP_SENSITIVITY = "SCALP_SENSITIVITY"
EXCLUDED_OPTION_ORAL_TREATMENT = DECISION_PATH_ORAL_TREATMENT

RULE_EXCLUDE_ORAL_FOR_HYPERTENSION = "RULE_EXCLUDE_ORAL_FOR_HYPERTENSION_V1"
RULE_CARDIO_COMORBIDITY_MANUAL_REVIEW = "RULE_CARDIO_COMORBIDITY_MANUAL_REVIEW_V1"
RULE_PRIOR_SIDE_EFFECTS_MANUAL_REVIEW = "RULE_PRIOR_SIDE_EFFECTS_MANUAL_REVIEW_V1"
RULE_SUPPORT_PATH_SCALP_SENSITIVITY = "RULE_SUPPORT_PATH_SCALP_SENSITIVITY_V1"
RULE_SUPPORT_PATH_LOW_CONSISTENCY = "RULE_SUPPORT_PATH_LOW_CONSISTENCY_V1"
RULE_SUPPORT_PATH_COMFORT_PRIORITY = "RULE_SUPPORT_PATH_COMFORT_PRIORITY_V1"
RULE_SUPPORT_PATH_SIMPLER_ROUTINE_PREFERENCE = "RULE_SUPPORT_PATH_SIMPLER_ROUTINE_PREFERENCE_V1"
RULE_NEEDS_MORE_INFORMATION_UNKNOWN_INPUTS = "RULE_NEEDS_MORE_INFORMATION_UNKNOWN_INPUTS_V1"
RULE_DEFAULT_SAFEST_START = "RULE_DEFAULT_SAFEST_START_V2"

JOURNEY_STATES = ["month_0", "week_6", "month_3", "month_6"]
